<?php 

               if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
     'key' => 'group_6195fb9333ff1',
     'title' => 'Pers',
     'fields' => array(
          array(
               'key' => 'field_6195fba10dbcb',
               'label' => 'bijlage',
               'name' => 'bijlage-pers',
               'type' => 'radio',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'choices' => array(
                    'pdf' => 'pdf',
                    'geluidsbestand' => 'geluidsbestand',
                    'vimeo' => 'vimeo',
                    'youtube' => 'youtube',
                    'soundcloud' => 'soundcloud',
                    'externe link' => 'externe link',
                    'interne link' => 'interne link',
               ),
               'allow_null' => 1,
               'other_choice' => 0,
               'default_value' => '',
               'layout' => 'vertical',
               'return_format' => 'value',
               'save_other_choice' => 0,
          ),
          array(
               'key' => 'field_6195fc2c0dbcc',
               'label' => 'geluidsfragment',
               'name' => 'geluidsfragment-pers',
               'type' => 'file',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => array(
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'geluidsbestand',
                         ),
                    ),
               ),
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'return_format' => 'url',
               'library' => 'all',
               'min_size' => '',
               'max_size' => '',
               'mime_types' => '',
          ),
          array(
               'key' => 'field_6195fe5136765',
               'label' => 'logo',
               'name' => 'logo-pers',
               'type' => 'image_aspect_ratio_crop',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => array(
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'pdf',
                         ),
                    ),
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'geluidsbestand',
                         ),
                    ),
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'externe link',
                         ),
                    ),
               ),
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'crop_type' => 'pixel_size',
               'aspect_ratio_width' => 280,
               'aspect_ratio_height' => 130,
               'return_format' => 'url',
               'preview_size' => 'medium',
               'library' => 'all',
               'min_width' => 280,
               'min_height' => 130,
               'min_size' => '',
               'max_width' => '',
               'max_height' => '',
               'max_size' => '',
               'mime_types' => '',
          ),
          array(
               'key' => 'field_6196008531384',
               'label' => 'externe link',
               'name' => 'externe-link-pers',
               'type' => 'url',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => array(
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'externe link',
                         ),
                    ),
               ),
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'default_value' => '',
               'placeholder' => '',
          ),
          array(
               'key' => 'field_6196051b2fcc4',
               'label' => 'youtube/vimeo/soundcloud',
               'name' => 'embedvideo-pers',
               'type' => 'oembed',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => array(
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'youtube',
                         ),
                    ),
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'vimeo',
                         ),
                    ),
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'soundcloud',
                         ),
                    ),
               ),
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'width' => 280,
               'height' => 157,
          ),
          array(
               'key' => 'field_61965a8451e74',
               'label' => 'beschrijving',
               'name' => 'beschrijving-pers',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => array(
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'pdf',
                         ),
                    ),
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'externe link',
                         ),
                    ),
               ),
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'default_value' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
               'maxlength' => '',
          ),
          array(
               'key' => 'field_61965c69d49c3',
               'label' => 'pdf-bestand',
               'name' => 'pdf-pers',
               'type' => 'file',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => array(
                    array(
                         array(
                              'field' => 'field_6195fba10dbcb',
                              'operator' => '==',
                              'value' => 'pdf',
                         ),
                    ),
               ),
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'return_format' => 'url',
               'library' => 'all',
               'min_size' => '',
               'max_size' => '',
               'mime_types' => '',
          ),
     ),
     'location' => array(
          array(
               array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'indepers',
               ),
          ),
     ),
     'menu_order' => -999,
     'position' => 'acf_after_title',
     'style' => 'default',
     'label_placement' => 'top',
     'instruction_placement' => 'label',
     'hide_on_screen' => '',
     'active' => true,
     'description' => '',
     'show_in_rest' => 0,
));

acf_add_local_field_group(array(
     'key' => 'group_61a22249638e6',
     'title' => 'Blokje',
     'fields' => array(
          array(
               'key' => 'field_61a2225068855',
               'label' => 'icoon',
               'name' => 'icoon_blokje',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'default_value' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
               'maxlength' => '',
          ),
          array(
               'key' => 'field_61a2226a68856',
               'label' => 'beschrijving',
               'name' => 'beschrijving_blokje',
               'type' => 'wysiwyg',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'default_value' => '',
               'tabs' => 'all',
               'toolbar' => 'full',
               'media_upload' => 1,
               'delay' => 0,
          ),
          array(
               'key' => 'field_61a2228168857',
               'label' => 'afbeelding',
               'name' => 'afbeelding_blokje',
               'type' => 'image',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'return_format' => 'url',
               'preview_size' => 'medium',
               'library' => 'all',
               'min_width' => '',
               'min_height' => '',
               'min_size' => '',
               'max_width' => '',
               'max_height' => '',
               'max_size' => '',
               'mime_types' => '',
          ),
          array(
               'key' => 'field_61a222cb68858',
               'label' => 'url',
               'name' => 'url_blokje',
               'type' => 'url',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'default_value' => '',
               'placeholder' => '',
          ),
          array(
               'key' => 'field_61a2235fe8320',
               'label' => 'lees_meer',
               'name' => 'lees_meer_blokje',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
               ),
               'default_value' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
               'maxlength' => '',
          ),
     ),
     'location' => array(
          array(
               array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'blokje',
               ),
          ),
     ),
     'menu_order' => 0,
     'position' => 'normal',
     'style' => 'default',
     'label_placement' => 'top',
     'instruction_placement' => 'label',
     'hide_on_screen' => '',
     'active' => true,
     'description' => '',
     'show_in_rest' => 0,
));

endif;         