<?php 

if( function_exists('acf_add_local_field_group') ):

     acf_add_local_field_group(array(
          'key' => 'group_617cebbf4ccbe',
          'title' => 'In de Pers post',
          'fields' => array(
               array(
                    'key' => 'field_617cec1cfecea',
                    'label' => 'link',
                    'name' => 'link',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
               ),
               array(
                    'key' => 'field_617cec29feceb',
                    'label' => 'afbeelding logo',
                    'name' => 'afbeelding_logo',
                    'type' => 'image_aspect_ratio_crop',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'crop_type' => 'aspect_ratio',
                    'aspect_ratio_width' => 280,
                    'aspect_ratio_height' => 130,
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
               ),
               array(
                    'key' => 'field_617ced366dd05',
                    'label' => 'beschrijving',
                    'name' => 'beschrijving',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
               ),
               array(
                    'key' => 'field_617ced9a6dd06',
                    'label' => 'medium',
                    'name' => 'medium',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'choices' => array(
                         'bladen' => 'bladen',
                         'video' => 'video',
                         'radio' => 'radio',
                         'online' => 'online',
                         'blog' => 'blog',
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'vertical',
                    'return_format' => 'value',
                    'save_other_choice' => 0,
               ),
               array(
                    'key' => 'field_617cede46dd07',
                    'label' => 'youtube',
                    'name' => 'youtube',
                    'type' => 'oembed',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                         array(
                              array(
                                   'field' => 'field_617ced9a6dd06',
                                   'operator' => '==',
                                   'value' => 'video',
                              ),
                         ),
                    ),
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'width' => '',
                    'height' => '',
               ),
          ),
          'location' => array(
               array(
                    array(
                         'param' => 'post_type',
                         'operator' => '==',
                         'value' => 'indepers',
                    ),
               ),
          ),
          'menu_order' => 0,
          'position' => 'acf_after_title',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
     ));

endif;         
