<?php 
			if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6195fb9333ff1',
	'title' => 'Pers',
	'fields' => array(
		array(
			'key' => 'field_6195fba10dbcb',
			'label' => 'bijlage',
			'name' => 'bijlage-pers',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'pdf' => 'pdf',
				'geluidsbestand' => 'geluidsbestand',
				'vimeo' => 'vimeo',
				'youtube' => 'youtube',
				'soundcloud' => 'soundcloud',
				'externe link video' => 'externe link video',
				'externe link artikel / podcast' => 'externe link artikel / podcast',
				'interne link' => 'interne link',
			),
			'allow_null' => 1,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6195fc2c0dbcc',
			'label' => 'geluidsfragment',
			'name' => 'geluidsfragment-pers',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'geluidsbestand',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6195fe5136765',
			'label' => 'logo',
			'name' => 'logo-pers',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'pdf',
					),
				),
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'geluidsbestand',
					),
				),
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => '',
					),
				),
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'interne link',
					),
				),
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'externe link artikel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'crop_type' => 'aspect_ratio',
			'aspect_ratio_width' => 420,
			'aspect_ratio_height' => 195,
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6196008531384',
			'label' => 'externe link',
			'name' => 'externe-link-pers',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'externe link video',
					),
				),
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'externe link artikel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_6196051b2fcc4',
			'label' => 'youtube/vimeo/soundcloud',
			'name' => 'embedvideo-pers',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'youtube',
					),
				),
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'vimeo',
					),
				),
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'soundcloud',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => 280,
			'height' => 157,
		),
		array(
			'key' => 'field_61a87081f1e77',
			'label' => 'pdf',
			'name' => 'pdf-pers',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'pdf',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_61a873c71c251',
			'label' => 'beschrijving',
			'name' => 'beschrijving-pers',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_61a89c33f37de',
			'label' => 'afbeelding-video',
			'name' => 'afbeelding-video-pers',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => 'gebruik dit veld bij de video-categorie als er geen link is naar youtube e.d. maar een externe link en een plaatje',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6195fba10dbcb',
						'operator' => '==',
						'value' => 'externe link video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'crop_type' => 'pixel_size',
			'aspect_ratio_width' => 488,
			'aspect_ratio_height' => 312,
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 488,
			'min_height' => 312,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'indepers',
			),
		),
	),
	'menu_order' => -999,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'group_617e4de7a9faa',
	'title' => 'Titel excerpt',
	'fields' => array(
		array(
			'key' => 'field_617e4df48112a',
			'label' => 'Titel blokje op pagina Praktijkverhalen',
			'name' => 'titel_excerpt',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'category:ervaringen-coaching',
			),
		),
	),
	'menu_order' => -999,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
));

acf_add_local_field_group(array(
	'key' => 'group_617e3a3c8417c',
	'title' => 'Blokjes',
	'fields' => array(
		array(
			'key' => 'field_617e3a4f6aa4f',
			'label' => 'icoon',
			'name' => 'icoon_blokje',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'book' => 'book',
				'edit' => 'edit',
				'copy' => 'copy',
				'heart' => 'heart',
				'link' => 'link',
				'moon' => 'moon',
				'sun' => 'sun',
				'star' => 'star',
				'' => '',
				'music' => 'music',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_617e3a596aa50',
			'label' => 'url',
			'name' => 'url_blokje',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
		),
		array(
			'key' => 'field_617e3a766aa51',
			'label' => 'afbeelding',
			'name' => 'afbeelding_blokje',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6283478a9b388',
			'label' => 'afbeelding',
			'name' => 'afbeelding_blokje_crop',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'crop_type' => 'aspect_ratio',
			'aspect_ratio_width' => 420,
			'aspect_ratio_height' => 194,
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_617e3b706aa53',
			'label' => 'beschrijving',
			'name' => 'beschrijving_blokje',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_617e3b526aa52',
			'label' => 'lees meer',
			'name' => 'lees_meer_blokje',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'blokje',
			),
		),
	),
	'menu_order' => -55,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'group_5e56b49e385f7',
	'title' => 'In de Pers radio',
	'fields' => array(
		array(
			'key' => 'field_5e56b4af27809',
			'label' => 'radio',
			'name' => 'radio',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5e56b4c72780a',
					'label' => 'image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5e56b4df2780b',
					'label' => 'titel',
					'name' => 'titel',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e56b4eb2780c',
					'label' => 'audio',
					'name' => 'audio',
					'type' => 'audio_video_player',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'general_type' => 'both',
					'mime_types' => '',
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/indepersradio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'group_602a8fbda53a7',
	'title' => 'testimonial',
	'fields' => array(
		array(
			'key' => 'field_602a8fc99d107',
			'label' => 'naam',
			'name' => 'naam',
			'type' => 'text',
			'instructions' => 'de naam van wie het citaat is',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_602a900a9d108',
			'label' => 'testimonial tekst',
			'name' => 'testimonial_tekst',
			'type' => 'text',
			'instructions' => 'het citaat van de klant',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_602a90299d109',
			'label' => 'foto',
			'name' => 'foto',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => 'portretfoto van de klant. let er op dat deze bijgesneden gaat worden tot een cirkel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'crop_type' => 'aspect_ratio',
			'aspect_ratio_width' => 150,
			'aspect_ratio_height' => 150,
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_602a90709d10a',
			'label' => 'link',
			'name' => 'link',
			'type' => 'url',
			'instructions' => 'de url van het coaching verhaal waarheen verwezen wordt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_602a90a39d10b',
			'label' => 'linktekst',
			'name' => 'linktekst',
			'type' => 'text',
			'instructions' => 'De tekstlink aanduiding bv lees hier het verhaal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/testimonial',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
));

endif;		